### ISSUE TITLE
Polish README

### ISSUE THREAD

**Issue by GiggleLiu** [TensorBFS/CuTropicalGEMM.jl#17]
A good template to follow is (it just underwent a strict review of JOSS):
https://github.com/TensorBFS/TensorInference.jl

Some aspects that could be improved:
- [x] The benchmark should be less messy, like using `@btimes` instead of `@benchmark`. The benchmark plot is not very good (following the bad example in TropicalGEMM.). I like more with the previous bar plot.
- [x] Missing section: How to contribute.
- [x] Warn users that this package is under GPL license and explain why.

**Comment by GiggleLiu** [comment]
## JOSS Review checklist

> * [x]  **Repository:** Is the source code for this software available at the https://github.com/TensorBFS/TensorInference.jl?
> * [x]  **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
> * [x]  **Contribution and authorship:** Has the submitting author (@mroavi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
> * [x]  **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)
> * [x]  **Data sharing:** If the paper contains original data, data are accessible to the reviewers. If the paper contains no original data, please check this item.
> * [x]  **Reproducibility:** If the paper contains original results, results are entirely reproducible by reviewers. If the paper contains no original results, please check this item.
> * [x]  **Human and animal research:** If the paper contains original data research on humans subjects or animals, does it comply with [JOSS's human participants research policy and/or animal research policy](https://joss.readthedocs.io/en/latest/policies.html?highlight=animal#joss-policies)? If the paper contains no such data, please check this item.
> 
> ### Functionality
> * [x]  **Installation:** Does installation proceed as outlined in the documentation?
> * [x]  **Functionality:** Have the functional claims of the software been confirmed?
> * [x]  **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
> 
> ### Documentation
> * [x]  **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [x]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
> * [x]  **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
> * [x]  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
> * [ ]  **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
> * [x]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by ArrogantGao** [comment]
I revised the README file.
Some how the `@btime` macro still do not work, it seems that it will return the minimum time detected, which is not correct for our kernel, so when using our kernel I kept the `@benchmark` macro.

I also changed the benchmark result to the previous style, which is more clear. Later I will create a repo for detailed benchmarks.

License is changed as MIT license.
